### ISSUE TITLE
大哥，请教下，如何监听luquid上的交易对价格呢

### ISSUE THREAD

**Issue by MrReN** [xiang-xx/liquidswap-pool-example#1]

**Comment by xiang-xx** [comment]
获取 pool address 对应的 Resources，一般会有个特定的类型，取 resource 里的 x/y reserve，就是两种币的库存量，使用 https://github.com/OmniBTC/go-aptos-liquidswap 里的方法计算输入输出。

你可以看一下他网站上的请求，当你输入兑换数据的时候，他会从链上请求 resouce。
